In [10]:
%matplotlib notebook
import pandas as pd
import pathlib as path
import numpy as np
import matplotlib.pyplot as plt
import os
import requests
import hvplot.pandas
import datetime as dt
import seaborn as sns
from config import api_key
from pprint import pprint

In [11]:
# import data for Dollarama, Canadian_tire, and Linamar companies.

Dollarama_balance_sheet=pd.read_csv("Resource/Dollarama_balance_sheet.csv")
Dollarama_income_statement = pd.read_csv("Resource/Dollarama_income_tatement.csv")
Dollarama_cash_flow_statement = pd.read_csv("Resource/Dollarama_cash_flow_statement.csv")

Canadian_tire_balance_sheet = pd.read_csv("Resource/Canadian_tire_balance_sheet.csv")
Canadian_tire_income_statement = pd.read_csv("Resource/Canadian_tire_income_statement.csv")
Canadian_tire_cash_flow_statement = pd.read_csv("Resource/Canadian_tire_cash_flow_statement.csv")

Linamar_balance_sheet = pd.read_csv("Resource/Linamar_balance_sheet.csv")
Linamar_income_statement = pd.read_csv("Resource/Linamar_income_statement.csv")
Linamar_cash_flow_statement = pd.read_csv("Resource/Linamar_income_statement.csv")

In [12]:
#Dollarama_balance_sheet.head(10)
#Dollarama_income_statement.head(10)
#Dollarama_cash_flow_statement.head(10)

#Canadian_tire_balance_sheet.head(10)
#Canadian_tire_income_statement.head(10)
#Canadian_tire_cash_flow_statement.head(10)

#Linamar_balance_sheet.head(10)
#Linamar_income_statement.head(10)
Linamar_cash_flow_statement.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Linamar Corporation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Premium Export,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Income Statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,FY-9,FY-8,FY-7,FY-6,FY-5,FY-4,FY-3,FY-2,FY-1,FY
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Period End Date,2013-12-31,2014-12-31,2015-12-31,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-12-31,2021-12-31,2022-12-31
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Rename the columns.
Dollarama_balance_sheet=Dollarama_balance_sheet.rename(columns=        
         { "Unnamed: 0": "Dollarama",
          'Unnamed: 1':'2014',
          'Unnamed: 2':'2015',
          'Unnamed: 3':'2016', 
          'Unnamed: 4':'2017',
          'Unnamed: 5':"2018", 
          'Unnamed: 6':'2019',
          'Unnamed: 7':'2020', 
          'Unnamed: 8':'2021',
          'Unnamed: 9':'2022',
          'Unnamed: 10': '2023'})

Dollarama_income_statement = Dollarama_income_statement.rename(columns=        
         { "Unnamed: 0": "Dollarama",
          'Unnamed: 1':'2014',
          'Unnamed: 2':'2015',
          'Unnamed: 3':'2016', 
          'Unnamed: 4':'2017',
          'Unnamed: 5':"2018", 
          'Unnamed: 6':'2019',
          'Unnamed: 7':'2020', 
          'Unnamed: 8':'2021',
          'Unnamed: 9':'2022',
          'Unnamed: 10': '2023'})

Dollarama_cash_flow_statement = Dollarama_cash_flow_statement.rename(columns=        
         { "Unnamed: 0": "Dollarama",
          'Unnamed: 1':'2014',
          'Unnamed: 2':'2015',
          'Unnamed: 3':'2016', 
          'Unnamed: 4':'2017',
          'Unnamed: 5':"2018", 
          'Unnamed: 6':'2019',
          'Unnamed: 7':'2020', 
          'Unnamed: 8':'2021',
          'Unnamed: 9':'2022',
          'Unnamed: 10': '2023'})


Canadian_tire_balance_sheet = Canadian_tire_balance_sheet.rename(columns=        
         { "Canadian Tire Corporation Limited": "Canadian Tire",
          'Unnamed: 1':'2013',
          'Unnamed: 2':'2014',
          'Unnamed: 3':'2015', 
          'Unnamed: 4':'2016',
          'Unnamed: 5':"2017", 
          'Unnamed: 6':'2018',
          'Unnamed: 7':'2019', 
          'Unnamed: 8':'20201',
          'Unnamed: 9':'2021',
          'Unnamed: 10': '2022'})

Canadian_tire_income_statement = Canadian_tire_income_statement.rename(columns=        
         { "Unnamed: 0": "Canadian Tire",
          'Unnamed: 1':'2013',
          'Unnamed: 2':'2014',
          'Unnamed: 3':'2015', 
          'Unnamed: 4':'2016',
          'Unnamed: 5':"2017", 
          'Unnamed: 6':'2018',
          'Unnamed: 7':'2019', 
          'Unnamed: 8':'20201',
          'Unnamed: 9':'2021',
          'Unnamed: 10': '2022'})

Canadian_tire_cash_flow_statement = Canadian_tire_cash_flow_statement.rename(columns=        
         { "Unnamed: 0": "Canadian Tire",
          'Unnamed: 1':'2013',
          'Unnamed: 2':'2014',
          'Unnamed: 3':'2015', 
          'Unnamed: 4':'2016',
          'Unnamed: 5':"2017", 
          'Unnamed: 6':'2018',
          'Unnamed: 7':'2019', 
          'Unnamed: 8':'20201',
          'Unnamed: 9':'2021',
          'Unnamed: 10': '2022'})

Linamar_balance_sheet = Linamar_balance_sheet.rename(columns=        
         { "Unnamed: 0": "Linamar",
          'Unnamed: 1':'2013',
          'Unnamed: 2':'2014',
          'Unnamed: 3':'2015', 
          'Unnamed: 4':'2016',
          'Unnamed: 5':"2017", 
          'Unnamed: 6':'2018',
          'Unnamed: 7':'2019', 
          'Unnamed: 8':'20201',
          'Unnamed: 9':'2021',
          'Unnamed: 10': '2022'})

Linamar_income_statement = Linamar_income_statement.rename(columns=        
         { "Unnamed: 0": "Linamar",
          'Unnamed: 1':'2013',
          'Unnamed: 2':'2014',
          'Unnamed: 3':'2015', 
          'Unnamed: 4':'2016',
          'Unnamed: 5':"2017", 
          'Unnamed: 6':'2018',
          'Unnamed: 7':'2019', 
          'Unnamed: 8':'20201',
          'Unnamed: 9':'2021',
          'Unnamed: 10': '2022'})

Linamar_cash_flow_statement = Linamar_cash_flow_statement.rename(columns=        
         { "Unnamed: 0": "Linamar",
          'Unnamed: 1':'2013',
          'Unnamed: 2':'2014',
          'Unnamed: 3':'2015', 
          'Unnamed: 4':'2016',
          'Unnamed: 5':"2017", 
          'Unnamed: 6':'2018',
          'Unnamed: 7':'2019', 
          'Unnamed: 8':'20201',
          'Unnamed: 9':'2021',
          'Unnamed: 10': '2022'})

In [5]:
# For test
#Dollarama_balance_sheet.head(10)
#Dollarama_income_statement.head(10)
#Dollarama_cash_flow_statement.head(10)

#Canadian_tire_balance_sheet.head(10)
#Canadian_tire_income_statement.head(10)
#Canadian_tire_cash_flow_statement.head(10)

#Linamar_balance_sheet.head(10)
#Linamar_income_statement.head(10)
#Linamar_cash_flow_statement.head(10)

In [14]:
# Clean data for Dollarama
Dollarama_balance_sheet = Dollarama_balance_sheet.loc[Dollarama_balance_sheet["Dollarama"] != 'Period End Date']
Dollarama_balance_sheet = Dollarama_balance_sheet.set_index("Dollarama")
Dollarama_balance_sheet = Dollarama_balance_sheet.dropna(how='any')

Dollarama_income_statement = Dollarama_income_statement.loc[Dollarama_income_statement["Dollarama"] != 'Period End Date']
Dollarama_income_statement = Dollarama_income_statement.set_index("Dollarama")
Dollarama_income_statement = Dollarama_income_statement.dropna(how='any')

Dollarama_cash_flow_statement = Dollarama_cash_flow_statement.loc[Dollarama_cash_flow_statement["Dollarama"] != 'Period End Date']
Dollarama_cash_flow_statement = Dollarama_cash_flow_statement.set_index("Dollarama")
Dollarama_cash_flow_statement = Dollarama_cash_flow_statement.dropna(how='any')

# Clean data for Canadian_tire
Canadian_tire_balance_sheet = Canadian_tire_balance_sheet.loc[Canadian_tire_balance_sheet["Canadian Tire"] != 'Period End Date']
Canadian_tire_balance_sheet = Canadian_tire_balance_sheet.set_index("Canadian Tire")
Canadian_tire_balance_sheet = Canadian_tire_balance_sheet.dropna(how='any')

Canadian_tire_income_statement = Canadian_tire_income_statement.loc[Canadian_tire_income_statement["Canadian Tire"] != 'Period End Date']
Canadian_tire_income_statement = Canadian_tire_income_statement.set_index("Canadian Tire")
Canadian_tire_income_statement = Canadian_tire_income_statement.dropna(how='any')


Canadian_tire_cash_flow_statement = Canadian_tire_cash_flow_statement.loc[Canadian_tire_cash_flow_statement["Canadian Tire"] != 'Period End Date']
Canadian_tire_cash_flow_statement = Canadian_tire_cash_flow_statement.set_index("Canadian Tire")
Canadian_tire_cash_flow_statement = Canadian_tire_cash_flow_statement.dropna(how='any')


# Clean data for Canadian_tire
Linamar_balance_sheet = Linamar_balance_sheet.loc[Linamar_balance_sheet["Linamar"] != 'Period End Date']
Linamar_balance_sheet = Linamar_balance_sheet.set_index("Linamar")
Linamar_balance_sheet = Linamar_balance_sheet.dropna(how='any')

Linamar_income_statement = Linamar_income_statement.loc[Linamar_income_statement["Linamar"] != 'Period End Date']
Linamar_income_statement = Linamar_income_statement.set_index("Linamar")
Linamar_income_statement = Linamar_income_statement.dropna(how='any')

Linamar_cash_flow_statement = Linamar_cash_flow_statement.loc[Linamar_cash_flow_statement["Linamar"] != 'Period End Date']
Linamar_cash_flow_statement = Linamar_cash_flow_statement.set_index("Linamar")
Linamar_cash_flow_statement = Linamar_cash_flow_statement.dropna(how='any')

In [15]:
# For test
#Dollarama_balance_sheet.head(10)
#Dollarama_income_statement.head(10)
#Dollarama_cash_flow_statement.head(10)

#Canadian_tire_balance_sheet.head(10)
#Canadian_tire_income_statement.head(10)
#Canadian_tire_cash_flow_statement.head(10)

#Linamar_balance_sheet.head(10)
#Linamar_income_statement.head(10)
#Linamar_cash_flow_statement.head(10)

# For test
Dollarama_balance_sheet_df = Dollarama_balance_sheet.transpose()
Dollarama_balance_sheet_df.head(10)

Dollarama_income_statement_df = Dollarama_income_statement.transpose()
#Dollarama_income_statement.head(10)

Dollarama_cash_flow_statement_df = Dollarama_cash_flow_statement.transpose()
#Dollarama_cash_flow_statement.head(10)

Canadian_tire_balance_sheet_df = Canadian_tire_balance_sheet.transpose()
Canadian_tire_income_statement_df = Canadian_tire_income_statement.transpose()
Canadian_tire_cash_flow_statement_df = Canadian_tire_cash_flow_statement.transpose()
Linamar_balance_sheet_df = Linamar_balance_sheet.transpose()
Linamar_income_statement_df = Linamar_income_statement.transpose()
Linamar_cash_flow_statement_df = Linamar_cash_flow_statement.transpose()

#Canadian_tire_balance_sheet.head(10)
#Canadian_tire_income_statement.head(10)
#Canadian_tire_cash_flow_statement.head(10)

#Linamar_balance_sheet.head(10)
#Linamar_income_statement.head(10)
#Linamar_cash_flow_statement_df.head(10)

In [ ]:
# Calculating the financial ratios
# Liquidity Ratios
# 1-Working capital ratio = Current assets / Current liabilities
# 2-Quick Ratio = Current assets – (Inventories / Current liabilities)
# 3-Operating cash flow ratio = Operating cash flow / Current liabilities

In [ ]:
#Risk Analysis Ratios
# 1-Debt to equity ratio = Total liabilities / Shareholder’s equity
# 2-Cash flow to debt ratio = Operating Cash Flow / Total Debt
# 3-Interest coverage ratio = Operating income / Interest expenses

In [ ]:
# Profitability Ratios
# 1-Gross Progit Margin = Revenue - Cost of sale / Revenue
# 2-Net profit margin = Net income / Sales
# 3-Return On Equity (ROE) = Net income / Shareholder’s equity
# 4-EPS = (Net income - Preferred dividends) / Average common shares outstanding

In [ ]:
# Efficiency Ratios
# 1-Inventory turnover ratio = Cost of goods / Average inventory
# 2-Working capital turnover ratio = Net Sales / Average Working Capital
# 3-Asset Turnover Ratio = Net Sales / Total Assets

In [ ]:
# Other Ratios
# 1- P/E Ratio= Market Price per Share / Earnings per Share (EPS)
# 2- Dividend Per Share

In [ ]:
# apikey = config.api_key
# api_key= LKG35AP5EYL6YUIJ
# base_url = https://www.alphavantage.co/query?
# parameter = function=TIME_SERIES_DAILY&
# sympole = symbol=SHOP.
# api_key = TRT&outputsize=full&apikey=demo
# combined_url = 
# pprint(combined_url)